---
k3s_version: v1.22.3+k3s1
ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable servicelb --flannel-backend=host-gw --kube-proxy-arg proxy-mode=ipvs --tls-san 10.18.8.1" 
extra_agent_args: "--kube-proxy-arg proxy-mode=ipvs"
