apiVersion: v1
kind: Namespace
metadata:
  name: adguard-home
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: adguard-home
  namespace: helmcharts
spec:
  repo: https://bjw-s.github.io/helm-charts
  chart: app-template
  targetNamespace: adguard-home
  valuesContent: |-
    image:
      repository: adguard/adguardhome
      pullPolicy: IfNotPresent
      tag: latest

    strategy:
      type: Recreate

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 80
          https:
            enabled: true
            port: 443
      node-port-dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.8.8.53
        ports:
          dns:
            enabled: true
            port: 53
            protocol: UDP

    ingress:
      main:
        enabled: true
        tls: 
          - hosts:
            - adguard.hand.technology
        hosts:
          - host: adguard.hand.technology
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
      # admin:
      #   enabled: false
      #   tls: 
      #     - hosts: 
      #       - adguard-admin.hand.technology
      #   hosts:
      #     - host: adguard-admin.hand.technology
      #       paths:
      #         - path: /
      #           pathType: Prefix
      #           service:
      #             port: 3000

    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Mi
        mountPath: /opt/adguardhome/conf
      work:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: /opt/adguardhome/work
