apiVersion: v1
kind: Namespace
metadata:
  name: grocy
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grocy
  namespace: helmcharts
spec:
  repo: https://bjw-s.github.io/helm-charts
  chart: app-template
  targetNamespace: grocy
  valuesContent: |-
    image:
      repository: lscr.io/linuxserver/grocy
      pullPolicy: Always
      tag: latest

    strategy:
      type: Recreate

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 80

    ingress:
      main:
        enabled: true
        tls: 
          - hosts:
            - grocy.hand.technology
        hosts:
          - host: grocy.hand.technology
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80

    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 50Mi
        mountPath: /config

    env:
      PUID: 1000
      PGID: 1000
      TZ: UTC
