apiVersion: v1
kind: Namespace
metadata:
  name: mqtt
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mqtt
  namespace: helmcharts
spec:
  repo: https://bjw-s.github.io/helm-charts
  chart: app-template
  targetNamespace: mqtt
  valuesContent: |-
    image:
      repository: eclipse-mosquitto
      pullPolicy: Always
      tag: "2.0"

    strategy:
      type: Recreate

    service:
      main:
        enabled: true
        type: LoadBalancer
        ports:
          http:
            enabled: true
            port: 9001
          listen:
            enabled: true
            port: 1883

    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            listener 1883
            persistence false
            log_dest stdout
            allow_anonymous true

    persistence:
      mqtt-config:
        enabled: true
        type: configMap
        name: mqtt-config
        mountPath: /mosquitto/config

    probes:
      startup:
        enabled: false
      liveness:
        enabled: false
      readiness:
        enabled: false
