apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
## https://github.com/1Password/connect-helm-charts/blob/main/charts/connect
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: 1password-connect
  namespace: management-charts
spec:
  bootstrap: true
  repo: https://1password.github.io/connect-helm-charts
  chart: connect
  targetNamespace: 1password
---
## https://github.com/1Password/connect-helm-charts/blob/main/charts/connect/values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: 1password-connect
  namespace: management-charts
spec:
  bootstrap: true
  targetNamespace: 1password
  valuesContent: |-
    connect:
      serviceType: LoadBalancer
      loadBalancerIP: 10.18.8.123
      ingress:
        enabled: true
        hosts:
          - host: 1pass.hand.technology
            paths: ["/"]
