## https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  bootstrap: true
  valuesContent: |-
    # https://docs.traefik.io/observability/logs/
    logs:
      access:
        enabled: true
        fields:
          headers:
            defaultMode: keep
    service:
      spec:
        externalTrafficPolicy: Local
        loadBalancerIP: 10.18.8.80
    tlsStore:
      default:
        defaultCertificate:
          secretName: tls-wildcard-hand-technology
    deployment:
      dnsPolicy: ClusterFirstWithHostNet
