apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer-hand-technology
spec:
  acme:
    email: keith@khand.dev
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key-hand-technology
    solvers:
    - selector:
        dnsZones:
          - "hand.technology"
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret-hand-technology
            key: api-token
