chart:
  name: app-template
  repo: https://bjw-s.github.io/helm-charts
namespace: home-assistant
values:
  image:
    pullPolicy: Always
    repository: ghcr.io/home-assistant/home-assistant
    tag: stable
  ingress:
    main:
      enabled: true
      hosts:
      - host: hass.hand.technology
        paths:
        - path: /
          pathType: Prefix
          service:
            port: 80
      tls:
      - hosts:
        - hass.hand.technology
  persistence:
    config:
      accessMode: ReadWriteOnce
      enabled: true
      mountPath: /config
      size: 500Mi
      type: pvc
  service:
    main:
      enabled: true
      ports:
        http:
          enabled: true
          port: 80
          targetPort: 8123
      type: ClusterIP
  strategy:
    type: Recreate